name: Create Trigger Workflow 
 
on: 
  create: 
 
jobs: 
  create-job: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Show Event 
        run: echo "Action = Branch or Tag Created" 
 
      - name: Show Ref Type 
        run: echo "Type = ${{ github.event.ref_type }}" 
 
      - name: Show Ref Name 
        run: echo "Name = ${{ github.event.ref }}" 
 
      - name: Show Repository 
        run: echo "Repository = ${{ github.repository }}" 
 
      - name: Show User 
        run: echo "Created By = ${{ github.actor }}" 
 
      - name: Success 
        run: echo "Create Trigger Executed Successfully!"